### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin

### ISSUE THREAD

**Issue by nikklass** [little-pinecone/spring-boot-angular-scaffolding#1]
Hi,

Thanks for this repo.

Running mvn clean install generates the following error:

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm run build) on project frontend: Failed to run task: 'npm run build' failed. org.apache.commons
.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm run build) on project frontend: Failed to run
task
```

My work environment:

```
$ npm -v
6.10.2

$ node -v
v10.16.0
```

What could the problem be?

Nikk

**Comment by little-pinecone** [comment]
Hi,
I can't replicate this error in my environment. I found [this issue](https://github.com/eirslett/frontend-maven-plugin/issues/548), where somebody fixed a similar issue by removing eirslett from their m2 repository.

Your local version of npm should not be a problem, as the plugin installs the version given in the frontend pom.xml file.
As for the Maven and JDK, right now I use:
` mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-55-generic", arch: "amd64", family: "unix"
`
But the project is built correctly also on the environment with Java8 ($ export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64).

I pushed an updated project on the develop branch (updates in pom and package.json), you can try to check out to develop, pull my changes (with the https://github.com/little-pinecone/spring-boot-angular-scaffolding/commit/7991398aac11c6a926cf0d83967a2322f600c8d1 commit) and try to run $mvn clean install there. The npm audit finds no vulnerabilities on the develop branch:
`spring-boot-angular-scaffolding/frontend/src/main/angular$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 19178 scanned packages
` 
Below you can find my output when I build the frontend manually ($ npm run build):
`spring-boot-angular-scaffolding/frontend/src/main/angular$ npm run build

> angular@0.0.0 build /home/little_pinecone/projects/spring_boot_with_angular/spring-boot-angular-scaffolding/frontend/src/main/angular
> ng build --prod
                                                                                 
Date: 2019-07-29T15:54:16.404Z
Hash: 2de0e7bda2ba18566052
Time: 14824ms
chunk {0} runtime-es5.741402d1d47331ce975c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es5.d83c89f8f3b162ef8cc9.js (main) 154 kB [initial] [rendered]
chunk {2} polyfills-es5.ba12c162d5f93eae9902.js (polyfills) 111 kB [initial] [rendered]
                                                                                 
Date: 2019-07-29T15:54:28.053Z
Hash: 75c6d914add26ca98e9c
Time: 11627ms
chunk {0} runtime-es2015.858f8dd898b75fe86926.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es2015.fa43b540cb63890bbc07.js (main) 134 kB [initial] [rendered]
chunk {2} polyfills-es2015.444f9ad7571234916d9d.js (polyfills) 36.4 kB [initial] [rendered]
chunk {3} styles.09e2c710755c8867a460.css (styles) 0 bytes [initial] [rendered]
`
In my case everything is correct, but, maybe in your case, you will see more specific errors when trying to run $ npm run build from the console.

**Comment by amirensit** [comment]
I have same error here and even deleting `~/m2/repository/com/github/eirslett` and rebuild does not solve my problem.

**Comment by little-pinecone** [comment]
> I have same error here and even deleting `~/m2/repository/com/github/eirslett` and rebuild does not solve my problem.

**Comment by amirensit** [comment]
My problem was that I am using an old version of intellij with **bundled** maven (3.0.5).
Making the IDEA uses the last version of maven solves my problem.

**Comment by little-pinecone** [comment]
Unfortunately, I'm unable to replicate this issue. Running:`mvn clean install` works in my case.

Does running commands like `npm audit` or `npm run build` gives you any warnings or errors? If not, it may be an issue with the [frontend-maven-plugin library](https://github.com/eirslett/frontend-maven-plugin). You can find great documentation and usage examples in the [project README](https://github.com/eirslett/frontend-maven-plugin).

There was a new release for this library, 11 days ago - [1.8.0](https://github.com/eirslett/frontend-maven-plugin/releases). You can find all releases under the [https://repo1.maven.org/maven2/com/github/eirslett/frontend-maven-plugin/](https://repo1.maven.org/maven2/com/github/eirslett/frontend-maven-plugin/) link.

You can find similar issues in the repo [Issues tab](https://github.com/eirslett/frontend-maven-plugin/issues) - like [issue 740](https://github.com/eirslett/frontend-maven-plugin/issues/740) or [issue 378](https://github.com/gitbucket/gitbucket/issues/378).

I closed this issue accidentally. I will keep it open for some time in case any new feedback.

**Comment by RaedSboui** [comment]
i have the same error :

Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npm (npm build) on project front
end: Failed to run task: 'npm run-script build' failed. org.apache.commons.exec.ExecuteException: Process exited
with an error: -4058 (Exit value: -4058)

I need help



<plugins>
      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>1.12.0</version>
        <configuration>
          <nodeVersion>v14.15.4</nodeVersion>
          <npmVersion>6.14.11</npmVersion>
          <nodeDownloadRoot>https://npm.taobao.org/mirrors/node/</nodeDownloadRoot>
        </configuration>
        <executions>
          <execution>
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <phase>generate-resources</phase>
          </execution>
          <execution>
            <id>npm install</id>
            <goals>
              <goal>npm</goal>
            </goals>
            <configuration>
              <arguments>install</arguments>
            </configuration>
          </execution>
          <execution>
            <id>npm build</id>
            <goals>
              <goal>npm</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <arguments>run-script build</arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>

**Comment by little-pinecone** [comment]
Unfortunately, I'm unable to replicate this issue.

I updated the `frontend-maven-plugin` version to 1.12.0 and ran `mvn clean install` command. The project builds correctly according to my log output:

```
[INFO] --- frontend-maven-plugin:1.12.0:npm (npm run build) @ frontend ---
[INFO] Running 'npm run build' in /home/littlepinecone/projects/spring-boot-angular-scaffolding/frontend/src/main/angular
[INFO] 
[INFO] > angular@0.0.0 build
[INFO] > ng build --configuration production
[INFO] 
[INFO] - Generating browser application bundles (phase: setup)...
[INFO] ✔ Browser application bundle generation complete.
[INFO] ✔ Browser application bundle generation complete.
[INFO] - Copying assets...
[INFO] ✔ Copying assets complete.
[INFO] - Generating index html...
[INFO] ✔ Index html generation complete.
…
[INFO] Build at: 2021-08-20T07:19:51.314Z - Hash: d85f6a49f83e3271dd67 - Time: 12342ms

```

However, I found the [frontend-maven-plugin when it runs npm run build can't find package.json file](https://stackoverflow.com/questions/61986567/frontend-maven-plugin-when-it-runs-npm-run-build-cant-find-package-json-file) issue on StackOverflow where the `errno -4058` was caused by the `package.json` location not given in the `workingDirectory` property.

Maybe the error you're seeing has something to do with the way you configured the plugin in your `pom.xml` file? Can you see in your logs what caused the error?

I would recommend consulting the [Optional configuration](https://github.com/eirslett/frontend-maven-plugin#optional-configuration) section in the plugin documentation.

Furthermore, make sure that the Node.js version you use is compatible with your Angular version. [Angular requires](https://angular.io/guide/setup-local#prerequisites) an [active or maintenance LTS version](https://nodejs.org/en/about/releases/) of Node.js.

**Comment by hussainzakir** [comment]
I am facing the same issue not in my local but when I push my code in the github the build is failed Can anyone suggest any changes I can make. Thanks
